services:
  - type: web
    name: such-engine-rotor
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
